function name = TF_name(ind)

    if(ind == 1)
        name = 'ASCL1';
    elseif(ind == 2)
        name = 'FOXA1';
    elseif(ind == 3)
        name = 'FOXA2';    
    elseif(ind == 4)
        name = 'ELF3';
    elseif(ind == 5)
        name = 'RBPJ';
    elseif(ind == 6)
        name = 'FLI1';
    elseif(ind == 7)
        name = 'SMAD4';    
    elseif(ind == 8)
        name = 'NR0B2';
    elseif(ind == 9)
        name = 'NR0B1';
    elseif(ind == 10)
        name = 'BCL3';
    elseif(ind == 11)
        name = 'STAT6';
    elseif(ind == 12)
        name = 'ISL1';
    elseif(ind == 13)
        name = 'SOX11';
    elseif(ind == 14)
        name = 'CEBPD';
    elseif(ind == 15)
        name = 'EBF1';
    elseif(ind == 16)
        name = 'TCF4';
    elseif(ind == 17)
        name = 'RCOR2';
    elseif(ind == 18)
        name = 'TCF3';
    elseif(ind == 19)
        name = 'NEUROD2';
    elseif(ind == 20)
        name = 'OLIG2';
    elseif(ind == 21)
        name = 'MITF';
    elseif(ind == 22)
        name = 'SIX5';
    elseif(ind == 23)
        name = 'TEAD4';
    elseif(ind == 24)
        name = 'ZNF217';
    elseif(ind == 25)
        name = 'KLF2';
    elseif(ind == 26)
        name = 'GATA4';
    elseif(ind == 27)
        name = 'REST';
    elseif(ind == 28)
        name = 'HES1';
    elseif(ind == 29)
        name = 'RARG';
    elseif(ind == 30)
        name = 'MYCN';
    elseif(ind == 31)
        name = 'NEUROD1';
    elseif(ind == 32)
        name = 'GFI1B';
    elseif(ind == 33)
        name = 'POU2F3';
    elseif(ind == 34)
        name = 'YAP1';
    elseif(ind == 35)
        name = 'MYC';
    end

end